language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=Lua-5.1
    - LUA=Lua-5.2
    - LUA=Lua-5.3

before_install:
  - . .travis/setup.sh
  - luarocks install busted

install:
  - luarocks make

script:
  - ./tests.sh

notifications:
  email: false
